require('config.compe')
require('config.fugitive')
require('config.tab-completion')
require('config.telescope')
require('config.nvimtree')
require('config.navigator')
require('config.colorscheme')
require('config.highlights')
